-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQga17tR5ex0/YavKS0
Hv0JmQCtswWzveGKcyVfhd/10eSgCgYIKoZIzj0DAQehRANCAAR8Wjqs0t7BnSEE
GVm224AmYqB3ZRICKmy+FJ+gfJvhzl8iX/WRtijjey5gtu6TFF4csaLsvwRW/NQe
dAcklPFr
-----END PRIVATE KEY-----